#ifndef AUDIBLE_ALTIMETER_SAMPLE_ID_HPP
#define AUDIBLE_ALTIMETER_SAMPLE_ID_HPP

#include <array>
#include <cstdint>

enum class AUDIO_SAMPLE_ID {
  BEGIN_SAMPLES = 0,

  TWO = BEGIN_SAMPLES,
  THREE,
  ONE,

  NUM_SAMPLES,
  END_SAMPLES = NUM_SAMPLES
};

#endif  // AUDIBLE_ALTIMETER_SAMPLE_ID_HPP