////////////////////////////////////////////////////////////////////////////////
///////////////////// THIS FILE IS AUTOGENERATED ///////////////////////////////
///////////////////// DO NOT EDIT !!!!!!        ////////////////////////////////
/// created by
/// /Users/si/code/pico/vscode_picoexamples/Audbile-Altimeter/scripts/convert_audio_to_code.py
////////////////////////////////////////////////////////////////////////////////

#ifndef AUDIBLE_ALTIMETER_SAMPLE_ID_H
#define AUDIBLE_ALTIMETER_SAMPLE_ID_H

#include <cstdint>
constexpr std::size_t _TOTAL_NUMBER_OF_BYTES{290182};
enum class AUDIO_SAMPLE_ID {
  BEGIN_SAMPLES = 0,
  FOUR = BEGIN_SAMPLES,
  TWO,
  THREE,
  ONE,
  END_SAMPLES,
  NUM_SAMPLES = END_SAMPLES
};

#endif  // AUDIBLE_ALTIMETER_{AUDIO_SAMPLES_HEADER_FILE_NAME.upper()}_H
