////////////////////////////////////////////////////////////////////////////////
///////////////////// THIS FILE IS AUTOGENERATED ///////////////////////////////
///////////////////// DO NOT EDIT !!!!!!        ////////////////////////////////
/// created by /Users/si/code/pico/vscode_picoexamples/Audbile-Altimeter/scripts/convert_audio_to_code.py
////////////////////////////////////////////////////////////////////////////////

#ifndef AUDIBLE_ALTIMETER_AUDIO_SAMPLES_H
#define AUDIBLE_ALTIMETER_AUDIO_SAMPLES_H

#include <Audible-Altimeter/sample_id.hpp>

#include <cstdint>
#include <array>


struct Audio_sample_location_and_size {
    std::int16_t* location;
    std::size_t size;
};

constexpr std::size_t TOTAL_NUMBER_OF_BYTES { 290182 };
extern std::array<std::int16_t, 33000> four;
extern std::array<std::int16_t, 37736> two;
extern std::array<std::int16_t, 37952> three;
extern std::array<std::int16_t, 36403> one;

using sample_lookup_t = std::array<Audio_sample_location_and_size,
                        static_cast<std::size_t>(AUDIO_SAMPLE_ID::NUM_SAMPLES)>;
constexpr sample_lookup_t sample_lookup = {
    Audio_sample_location_and_size{ four.data(), four.size() },
    Audio_sample_location_and_size{ two.data(), two.size() },
    Audio_sample_location_and_size{ three.data(), three.size() },
    Audio_sample_location_and_size{ one.data(), one.size() },
    };
#endif // AUDIBLE_ALTIMETER_AUDIO_SAMPLES_H
